# Generated by Django 3.0.7 on 2021-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210823_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_id', models.CharField(max_length=50)),
            ],
        ),
    ]
