# Generated by Django 3.0.7 on 2021-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
