# Generated by Django 3.0.7 on 2021-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210825_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
