# Generated by Django 3.0.7 on 2021-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210825_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(upload_to='media/shop/'),
        ),
    ]
