# Generated by Django 3.0.7 on 2021-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210825_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(default='profile.png', upload_to='media/shop/'),
        ),
    ]
